apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgDJxUdNb4QXcN7JS/wmRl8yhU6DuTFOghxvKMu4EbjO452n/710dJ55zRWox9hJvKRoxgANSu/heeDS4rTSlTioW5rYwhn+hMbFRqJTm7FwouolcxsjfYuNQtbZnNjiL3Z00cxs47Pl2A8PBWbWuEvHxxHWKbiua86RHPZ5zhDePTxkyDHoc1cYhG/Z1lHVs3e30cnANktAQQsI2+o097fjh160sQxgHOZT00RNltcHqXPAQMTKMWsdS2BXNt9EaKAQbHstkWztkvRy2/sTRpklnEu1cB3X81VXxiYWK/PQFk823zxWhC3Unus0QPJG/FUDPSWbp8bFe7VfOZ3toQDSmIP+jCc/IRP24REvH9V8Nl+EGdQU4GhhaCFi6gmCOvsU6mq2lRIw2em4zLl9xPlrOTkzXmzp83hy9uCCocZJB9wxEjmnZ3DEOMkl9YWwQbfURVXZSHE1cV0z/1wanw1DHw+ELfxnbRuRtMWSbJ3GRXvNKBo/mQ6ECbV2MxmEU8JjTbxyGNMB8R4oZSPyQw9tnuZ16cjL1n4oBU7N5TDKww0KDmmw2jrXvL4KidlLVk8tO2mC2m7+24STtkVqlKj7lFrkZuqtpuLEDuR4/uMvAWZUyfGflUFKyJfGWWBjSaMuh+xDPLGnrZDs0XCpAfejfBTHv3BZmRL1yMOMElL2Ic6ybsBlnejFsUz9vS1fmtnFPu+EIATsnjUBkptIRBr5PlBQ0YJXHGTN2DCWOf7hJgM5mGSxxVTeUbVx5z823NfuvVDha7SQe0qhU3Jm0WpeSswB4daFKNTvUPifDG5B+1jNFCTDuvcbGlBRskJyPXVobZiaCH/3x32vCcF9XSLRXTBzXwEQlOzJIUd6VRv201UMWPldCkKTgOeI513dN4r9SeeZOw13u0wuRAcNmgHfzR7eTBPLkZRFwoMVDscRI36vzmXHaCt4L24K+kk1MgF5svAlWLqVQm6dk+urJOnZ6Ne4r4FChnr8PV25qRv7U2oj3OWo+FEhModcVHC8vQCr+b2YoVP3QH+/dxQs55r7hxdnJB25WI2BXBJj/w7/TkE185r5miQSH1by6BiXNX5XB1dJk4fmI3N+SpwiN7pcwhAEZTVVAXd+TBGQQV/tKKNj/ZbRMuRKGAFM27gN2xrlE/UFsDC+1Xv6bbrXIkpeXZOG2+hQJK9pjCR6h6Q2F7v34BgP2wKBpUskq2C0gxkxGKZSHp+6tLoNDhK2NKEAsrDPCwhFik/VqqODp9ZmsIQrRFxqCVJKpVsGPgvOavdF9OsEOEEt8RDGraXgp9jVR452OlYJyDkjcH0SNW+Xo0SBli9X+HaJj6eSCCFdtiCd
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

