apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-image-registry-image-registry
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-image-registry
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-image-registry/image-registry
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-image-registry-ocp4.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
