apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: quay-io
  namespace: gitops-image-registry
spec:
  encryptedData:
    .dockerconfigjson: AgC/ax58KS6QTgTQ6TkSIoge+vQct6sIRq6SisEHT/p0BW+DAZFma5wkiA9fLnC/abx/Uag6aDHZabqYPsto6gFM4YW0NLvASz+/K+7LOgkrvVpzmwOBUOxiYxC3cthkZRxY2mCuw1NSO2+tO/pogCwvkVzLCmrsDW96otbQJ9qHr7g2RFdOGFpq/ydHAA6+YLKwUAsdvxe/HXM1iHBP2DxZJQUc9Kd0UI/LLDSJvhbTYKnPjbyXKhRL+1Vg3jGgcKv+eGYeEq3MKWyjgnhkrSfDnlIFTivelGQrRGjDo6wsKDemODDwQkTMlkN3TYNzgcba9ZSGex0jwaKfjvqhl0w0tjoMkLnZGo2cX0ZisHHYFpMLU8OM0u7Do5WFFWdc8KtHbXS5lO5jjR9XvUIMdon8g9bFEhCQfMCbw2wzIc0SHYFvsyyE7CBXKn8qQDiaIWjIXudwqnCUJKtZgsjtss7t3iqxPrYPRuYaJxxoWA5RoIfuDBIj4013RsloURtR63eyNVs+aPi5I+DuG3pbmMFWpCZv1rRc3kdIXLOtBzKW5W5L0IxavkXb1nebEsE4cOHwAyjpOotmAYOhktbLZGvNk3HN9tqG+UZzlCq2GDnZAdr+Njg/irLIuTpVEL8l4KE/iDF20BlEs7DMHzk4cVSwRcHDxkg5GUQ4LImllXSQjJtEG/e4VbygpqawLBIiXEvKEVZOXbdnNo7VDYu+d+fyT5Hu/Zv++OAxhrG3adpR4P63ogHLfKL84F4+H5pviy89Sv7JBwgjv4ZeMfZLnPgpfaw49R7KYJXVTS9/aBylFM/B7iRaqtxXykxBEZggpwQVQTnBnjbGA9W+1B8HxG2yzPFEY2H/WbXGvp8tyJjUetH907RVKJWByp2C3zwG
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        image-registry/push: "true"
      name: quay-io
      namespace: gitops-image-registry
    type: kubernetes.io/dockerconfigjson

